In [68]:
"""Nero Dual-Arm Core Functions Test"""
from nero.teleop.nero_dual_arm import NeroDualArm
from nero.teleop.nero_teleop_config import NeroDualArmConfig
import logging
import numpy as np
import time

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

In [69]:
"""Test 1: Configuration"""
config = NeroDualArmConfig(
    robot_ip='192.168.110.114',
    robot_port=4242,
    use_gripper=True,
    debug=False
)
print("Config created:", config)
print(f"  - robot_ip: {config.robot_ip}")
print(f"  - robot_port: {config.robot_port}")
print(f"  - use_gripper: {config.use_gripper}")
print(f"  - debug: {config.debug}")

Config created: NeroDualArmConfig(id=None, calibration_dir=None, name='nero_dual_arm', robot_ip='192.168.110.114', robot_port=4242, gripper_ip='192.168.110.114', gripper_port=4243, use_gripper=True, gripper_max_open=0.1, gripper_force=2.0, gripper_reverse=False, close_threshold=0.05, control_mode='oculus', debug=False, num_joints_per_arm=7, cameras={}, max_joint_velocity=2.0, max_ee_velocity=0.5, max_joint_delta=0.3)
  - robot_ip: 192.168.110.114
  - robot_port: 4242
  - use_gripper: True
  - debug: False


In [70]:
"""Test 2: Robot Instance Creation"""
robot = NeroDualArm(config)
print(f"Robot instance created: {robot}")
print(f"  - name: {robot.name}")
print(f"  - is_connected: {robot.is_connected}")

Robot instance created: None NeroDualArm
  - name: nero_dual_arm
  - is_connected: False


In [71]:
"""Test 3: Motor Features"""
motor_features = robot.motor_features
print(f"Motor features ({len(motor_features)} keys):")
print(f"  - Left arm joints: {len([k for k in motor_features if 'left_joint' in k])}")
print(f"  - Right arm joints: {len([k for k in motor_features if 'right_joint' in k])}")
print(f"  - Left EE pose: {len([k for k in motor_features if 'left_ee_pose' in k])}")
print(f"  - Right EE pose: {len([k for k in motor_features if 'right_ee_pose' in k])}")

Motor features (30 keys):
  - Left arm joints: 7
  - Right arm joints: 7
  - Left EE pose: 6
  - Right EE pose: 6


In [72]:
"""Test 4: Action Features"""
action_features = robot.action_features
print(f"Action features ({len(action_features)} keys):")
print(f"  - Left joint pos: {len([k for k in action_features if 'left_joint' in k and 'pos' in k])}")
print(f"  - Right joint pos: {len([k for k in action_features if 'right_joint' in k and 'pos' in k])}")
print(f"  - Left delta EE: {len([k for k in action_features if 'left_delta_ee_pose' in k])}")
print(f"  - Right delta EE: {len([k for k in action_features if 'right_delta_ee_pose' in k])}")

Action features (28 keys):
  - Left joint pos: 7
  - Right joint pos: 7
  - Left delta EE: 6
  - Right delta EE: 6


In [73]:
"""Test 5: Connect to Robot"""
robot.connect()
print(f"Connected: {robot.is_connected}")

INFO:nero.teleop.nero_dual_arm:
INFO:nero.teleop.nero_dual_arm:[ROBOT] Connecting to Nero Dual-Arm System
INFO:nero.teleop.nero_dual_arm:============================================================
INFO:nero.teleop.nero_dual_arm:
===== [ROBOT] Connecting to Nero dual-arm =====
INFO:nero.teleop.interface.nero_interface_client:[CLIENT] Connected to 192.168.110.114:4242
INFO:nero.teleop.nero_dual_arm:[LEFT ARM] End-effector pose: [np.float64(-0.2764), np.float64(-0.028), np.float64(0.3861), np.float64(1.6065), np.float64(-0.0669), np.float64(-0.0166)]
INFO:nero.teleop.nero_dual_arm:[RIGHT ARM] End-effector pose: [np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0)]
INFO:nero.teleop.nero_dual_arm:===== [ROBOT] Nero dual-arm connected successfully =====

INFO:nero.teleop.nero_dual_arm:
===== [GRIPPER] Initializing grippers =====


[-0.276374   -0.027976    0.386089    1.6064534  -0.06693338 -0.01659808]
[0. 0. 0. 0. 0. 0.]
Nero dual-arm connected successfully.


INFO:nero.teleop.nero_dual_arm:[LEFT GRIPPER] Initialized successfully
INFO:nero.teleop.nero_dual_arm:[RIGHT GRIPPER] Initialized successfully
INFO:nero.teleop.nero_dual_arm:===== [GRIPPER] Grippers initialized successfully =====

INFO:nero.teleop.nero_dual_arm:[INFO] nero_dual_arm initialization completed successfully.



Connected: True


In [ ]:
"""Test 6: Get Observation"""
obs = robot.get_observation()
print(f"Observation keys ({len(obs)}):")
print("  Left arm joints:")
for i in range(7):
    key = f'left_joint_{i+1}.pos'
    print(f"    {key}: {obs[key]:.4f}")
print("  Right arm joints:")
for i in range(7):
    key = f'right_joint_{i+1}.pos'
    print(f"    {key}: {obs[key]:.4f}")
print("  Left EE pose:")
for axis in ['x', 'y', 'z', 'rx', 'ry', 'rz']:
    key = f'left_ee_pose.{axis}'
    print(f"    {key}: {obs[key]:.4f}")
print("  Right EE pose:")
for axis in ['x', 'y', 'z', 'rx', 'ry', 'rz']:
    key = f'right_ee_pose.{axis}'
    print(f"    {key}: {obs[key]:.4f}")

In [79]:
"""Test 7: Reset Robot"""
robot.reset()
print("Robot reset completed!")
time.sleep(1)
obs_after_reset = robot.get_observation()
print("Observation after reset:")
print(f"  Left EE x: {obs_after_reset['left_ee_pose.x']:.4f}")
print(f"  Right EE x: {obs_after_reset['right_ee_pose.x']:.4f}")

INFO:nero.teleop.nero_dual_arm:[ROBOT] Resetting dual-arm system...


RemoteError: Traceback (most recent call last):
  File "/home/keyz/miniconda3/envs/agilex_teleop/lib/python3.10/site-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/home/keyz/miniconda3/envs/agilex_teleop/lib/python3.10/site-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/home/keyz/miniconda3/envs/agilex_teleop/lib/python3.10/site-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "/home/keyz/Documents/projects/Robot/wbcd/lerobot/agilex_ws/agilex_teleop/nero/teleop/interface/nero_interface_server.py", line 512, in robot_go_home
    self.right_robot_go_home()
  File "/home/keyz/Documents/projects/Robot/wbcd/lerobot/agilex_ws/agilex_teleop/nero/teleop/interface/nero_interface_server.py", line 444, in right_robot_go_home
    self.right_robot.reset()
  File "/home/keyz/Documents/projects/Robot/wbcd/lerobot/agilex_ws/agilex_teleop/pyAgxArm/protocols/can_protocol/drivers/nero/default/driver.py", line 605, in reset
    self._send_msg(msg)
  File "/home/keyz/Documents/projects/Robot/wbcd/lerobot/agilex_ws/agilex_teleop/pyAgxArm/protocols/can_protocol/drivers/core/arm_driver_abstract.py", line 66, in _send_msg
    self._ctx.get_comm().send(data)
AttributeError: 'NoneType' object has no attribute 'send'


In [77]:
"""Test 9: Send Cartesian Delta EE Action"""
obs = robot.get_observation()
action = {}
for i in range(7):
    action[f'left_joint_{i+1}.pos'] = 0.0
    action[f'right_joint_{i+1}.pos'] = 0.0
for axis in ['x', 'y', 'z', 'rx', 'ry', 'rz']:
    action[f'left_delta_ee_pose.{axis}'] = 0.0
    action[f'right_delta_ee_pose.{axis}'] = 0.0
action['left_delta_ee_pose.x'] = -0.05
action['left_gripper_cmd_width'] = 0.2
# action['right_delta_ee_pose.y'] = 0.01
result = robot.send_action(action)
print("Cartesian delta EE action sent!")
time.sleep(0.5)

[-0.05  0.    0.    0.    0.    0.  ]
[0. 0. 0. 0. 0. 0.]
Cartesian delta EE action sent!
Cartesian delta EE action sent!


In [ ]:
"""Test 11: Observation Features"""
obs_features = robot.observation_features
print(f"Observation features ({len(obs_features)} keys):")
print(f"  Motor features: {len(robot.motor_features)}")
print(f"  Camera features: {len(robot.cameras_features)}")

In [ ]:
"""Test 12: Camera Features (Empty)"""
cam_features = robot.cameras_features
print(f"Camera features: {cam_features}")

In [ ]:
"""Test 13: Calibration Status"""
print(f"is_calibrated: {robot.is_calibrated()}")

In [ ]:
"""Test 14: Disconnect Robot"""
robot.disconnect()
print(f"Disconnected: {not robot.is_connected}")